### ISSUE TITLE
Crawler fails Post NU6 network upgrade 

### ISSUE THREAD

**Issue by autotunafish** [runziggurat/zcash#261]
I'm not sure why but I believe it may have to do with the zcash-seeder lib which required an update shortly after the NU6 upgrade. Since the upgrade, the crawler fails with reset and timeout errors. https://github.com/zcash/zcash-seeder

**Comment by aphelionz** [comment]
@Rqnsom would be the one to check, but I'm not sure how much time they have currently :grimacing:

**Comment by autotunafish** [comment]
The solution appears to be changing the line in the link below to reflect the correct protocol version '170_120'. After that and recompiling, the crawler works again. Credit for this goes to Arya Solhi. I can file the appropriate PR if necessary but it's a single char change, seems trivial enough and if so then this issue can basically be closed! :partying_face: 
https://github.com/runziggurat/zcash/blob/32273156f7e7a14a766c2860ddee7e7321ad237a/src/protocol/message/constants.rs#L15

**Comment by aphelionz** [comment]
Yes please file the PR!
